[package]
name = "aoc2015"
version = "1.0.0"
authors = ["Sam Hindess <mail@sohcah.dev>"]
edition = "2018"
default-run = "aoc2015"

[profile.release]
opt-level = 3

[dependencies]
rust-crypto = "^0.2"
fancy-regex = "^0.4.1"